### PR TITLE
Update Bender.lock to reflect updated memory island dependency

### PR DESCRIPTION
**Pull request by Scheremo**
Updated the Bender.lock file

### CODE REVIEW

**Comment by micprog** [comment]
I see that some bender dependencies point to branch names: This can quickly lead to incompatibilities, e.g., when branches update with breaking changes. Versions are suggested, tags are a reasonable alternative (tags should always stay fixed), and commit hashes are, in my opinion, a necessary evil, but still better than branch names that can update, including breaking changes, without warning. I see this is the case here for `cheshire` and `snitch_cluster`. Other than this, the update looks good to me.

**Comment by Scheremo** [comment]
> I see that some bender dependencies point to branch names: This can quickly lead to incompatibilities, e.g., when branches update with breaking changes. Versions are suggested, tags are a reasonable alternative (tags should always stay fixed), and commit hashes are, in my opinion, a necessary evil, but still better than branch names that can update, including breaking changes, without warning. I see this is the case here for `cheshire` and `snitch_cluster`. Other than this, the update looks good to me.



> I see that some bender dependencies point to branch names: This can quickly lead to incompatibilities, e.g., when branches update with breaking changes. Versions are suggested, tags are a reasonable alternative (tags should always stay fixed), and commit hashes are, in my opinion, a necessary evil, but still better than branch names that can update, including breaking changes, without warning. I see this is the case here for `cheshire` and `snitch_cluster`. Other than this, the update looks good to me.

Should be fixed now!

**Review by micprog — APPROVED** [review]
LGTM :+1:

**Comment by Scheremo** [comment]
> LGTM 👍

I further changed the CVA6 URL to use https for consistency :)

**Comment by micprog** [comment]
> > LGTM 👍
> 
> I further changed the CVA6 URL to use https for consistency :)

That's a good call, thanks! I could argue in cheshire you're still pointing to a branch of cva6, but fine for me right now, I just recommend to update when you get around to it.

**Pull request merged**
